import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

const config: Config = {
  darkMode: ['class'],
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      fontFamily: {
        sans: [
          'var(--font-sans)',
          'Rubik',
          'Heebo',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        // Stitch "Pastel Pulse" type families. Hebrew glyphs fall through to Heebo.
        'pp-display': ['var(--font-pp-display)', 'var(--font-pp-hebrew)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'pp-body': ['var(--font-pp-body)', 'var(--font-pp-hebrew)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'pp-metric': ['32px', { lineHeight: '38px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'pp-headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'pp-headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'pp-headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'pp-headline-lg-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'pp-headline-md': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'pp-body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'pp-body-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'pp-body-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'pp-label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'pp-label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
      spacing: {
        'pp-xs': '0.25rem',
        'pp-sm': '0.5rem',
        'pp-md': '1rem',
        'pp-lg': '1.5rem',
        'pp-xl': '2rem',
        'pp-gutter': '1rem',
        'pp-gutter-mobile': '0.75rem',
        'pp-margin': '1.5rem',
        'pp-margin-mobile': '1.25rem',
        'pp-dock': '88px',
      },
      boxShadow: {
        soft: '0 1px 3px 0 hsl(222 47% 11% / 0.05), 0 1px 2px -1px hsl(222 47% 11% / 0.05)',
        'soft-md': '0 4px 6px -1px hsl(222 47% 11% / 0.07), 0 2px 4px -2px hsl(222 47% 11% / 0.07)',
        'soft-lg': '0 10px 15px -3px hsl(222 47% 11% / 0.08), 0 4px 6px -4px hsl(222 47% 11% / 0.08)',
        'soft-xl': '0 20px 25px -5px hsl(222 47% 11% / 0.09), 0 8px 10px -6px hsl(222 47% 11% / 0.09)',
        glow: '0 0 0 1px hsl(var(--primary) / 0.1), 0 8px 24px -4px hsl(var(--primary) / 0.3)',
        'glow-emerald': '0 0 0 1px hsl(var(--success) / 0.15), 0 8px 24px -4px hsl(var(--success) / 0.3)',
        // Stitch `.candy-shadow` / `.candy-shadow-hover`
        'pp-candy': '0 10px 30px -4px rgba(112, 100, 244, 0.08), 0 2px 8px -2px rgba(30, 30, 36, 0.04)',
        'pp-candy-hover': '0 16px 36px -6px rgba(112, 100, 244, 0.14), 0 4px 12px -2px rgba(30, 30, 36, 0.04)',
        'pp-dock': '0 18px 40px -12px rgba(30, 30, 36, 0.45)',
      },
      colors: {
        // Stitch Pastel Pulse palette (Material 3 roles), prefixed `pp-`.
        pp: {
          primary: '#5243d5',
          'on-primary': '#ffffff',
          'primary-container': '#6b5fef',
          'on-primary-container': '#fffbff',
          'primary-fixed': '#e3dfff',
          'primary-fixed-dim': '#c5c0ff',
          'on-primary-fixed': '#140067',
          'on-primary-fixed-variant': '#3c28bf',
          'inverse-primary': '#c5c0ff',
          periwinkle: '#7064f4',
          secondary: '#006b54',
          'on-secondary': '#ffffff',
          'secondary-container': '#63fbcf',
          'on-secondary-container': '#00725a',
          'secondary-fixed': '#63fbcf',
          'secondary-fixed-dim': '#3fdeb4',
          'on-secondary-fixed': '#002118',
          'on-secondary-fixed-variant': '#00513f',
          tertiary: '#894375',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#a65b8e',
          'on-tertiary-container': '#fffbff',
          'tertiary-fixed': '#ffd8ee',
          'tertiary-fixed-dim': '#ffade2',
          'on-tertiary-fixed': '#3b002f',
          'on-tertiary-fixed-variant': '#712e5e',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          background: '#fbf8ff',
          'on-background': '#1b1b21',
          surface: '#fbf8ff',
          'surface-bright': '#fbf8ff',
          'surface-dim': '#dbd9e1',
          'surface-tint': '#5546d7',
          'surface-variant': '#e4e1ea',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f5f2fb',
          'surface-container': '#efecf5',
          'surface-container-high': '#eae7ef',
          'surface-container-highest': '#e4e1ea',
          'subtle-inset': '#f1edf8',
          'on-surface': '#1b1b21',
          'on-surface-variant': '#474554',
          'inverse-surface': '#303036',
          'inverse-on-surface': '#f2eff8',
          outline: '#787586',
          'outline-variant': '#c8c4d7',
          obsidian: '#1e1e24',
          mint: '#55efc4',
          amber: '#fdcb6e',
          pink: '#fda7df',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))',
        },
        alert: {
          DEFAULT: 'hsl(var(--alert))',
          foreground: 'hsl(var(--alert-foreground))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
          foreground: 'hsl(var(--info-foreground))',
        },
      },
      borderRadius: {
        xl: 'calc(var(--radius) + 4px)',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        pp: '1rem',
        'pp-lg': '2rem',
        'pp-xl': '3rem',
      },
      keyframes: {
        'confetti-fall': {
          '0%': { transform: 'translateY(-10vh) rotate(0deg)', opacity: '1' },
          '100%': { transform: 'translateY(110vh) rotate(720deg)', opacity: '0.3' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'zoom-in-95': {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      animation: {
        'confetti-fall': 'confetti-fall linear forwards',
        'fade-in': 'fade-in 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
        'fade-out': 'fade-out 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
        'zoom-in-95': 'zoom-in-95 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slide-down 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-up': 'slide-up 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [animate],
};

export default config;
