import { BaseModel, Field, Model } from '@arbel/firebase-orm';
import type { AdStudioImageFormat } from '@growthos/shared';

/** The steps an autopilot run walks, in order. */
export const AD_STUDIO_RUN_STEPS = ['plan', 'script', 'image_concepts', 'images', 'clips', 'assemble'] as const;
export type AdStudioRunStepId = (typeof AD_STUDIO_RUN_STEPS)[number];

export const AD_STUDIO_RUN_STEP_STATUSES = ['pending', 'running', 'done', 'skipped', 'failed'] as const;
export type AdStudioRunStepStatus = (typeof AD_STUDIO_RUN_STEP_STATUSES)[number];

/** `awaiting_approval`: the plan, script and image ideas are ready and wait for the person to confirm them before anything is rendered. */
export const AD_STUDIO_RUN_STATUSES = ['running', 'awaiting_approval', 'done', 'failed', 'cancelled'] as const;
export type AdStudioRunStatus = (typeof AD_STUDIO_RUN_STATUSES)[number];

export interface AdStudioRunStep {
  id: AdStudioRunStepId;
  status: AdStudioRunStepStatus;
  /** Why a step was skipped or failed, as a stable code (e.g. `already_done`, `no_landing_page`, `quota_exceeded`). */
  reason: string | null;
  /** What the step produced so far, e.g. "3 of 6 images" - numbers only, the UI words them. */
  progress: { done: number; total: number } | null;
  started_on: string | null;
  finished_on: string | null;
}

/** What the person asked the autopilot to do. */
export interface AdStudioRunOptions {
  /** Run the deep plan first when the brief has none. */
  plan: boolean;
  /** Write and render image ads. */
  images: boolean;
  /** Placements to render each image concept in (when concepts are generated by this run). */
  imageFormats: AdStudioImageFormat[];
  /** Render and assemble the video. */
  video: boolean;
  /** The data environment the plan reads results from; null for the project default. */
  environmentId: string | null;
  /**
   * Stop after the plan, script and image ideas for the person to review and confirm before any
   * image or video is rendered (the costly part). On by default; runs saved before it existed read false.
   */
  confirmPlan?: boolean;
}

/**
 * One automated end-to-end run over a brief: plan -> script -> image concepts -> images -> video
 * clips -> assembled video. It is advanced one small step at a time (by the page's poll or an MCP
 * call), never inside one long request, and each step does only what is missing: a script, concept
 * or clip the person already has - or edited - is kept, so re-running after a change redoes only the
 * stale parts. Exporting stays a separate, deliberate act.
 */
@Model({
  reference_path: 'organizations/:organization_id/projects/:project_id/ad_studio_runs',
  path_id: 'ad_studio_run_id',
})
export class AdStudioRunModel extends BaseModel {
  @Field({ is_required: true })
  public organization_id!: string;

  @Field({ is_required: true })
  public project_id!: string;

  @Field({ is_required: true })
  public brief_id!: string;

  @Field({ is_required: true })
  public status!: AdStudioRunStatus;

  @Field({ is_required: true })
  public options!: AdStudioRunOptions;

  @Field({ is_required: true })
  public steps!: AdStudioRunStep[];

  /** A caller holding the lease is advancing the run; others wait until it expires. */
  @Field({ is_required: false })
  public lease_until?: string | null;

  @Field({ is_required: false })
  public lease_token?: string | null;

  @Field({ is_required: false })
  public failure_code?: string | null;

  @Field({ is_required: false })
  public failure_message?: string | null;

  @Field({ is_required: true })
  public started_by!: string;

  @Field({ is_required: true })
  public started_on!: string;

  @Field({ is_required: true })
  public last_advanced_on!: string;

  @Field({ is_required: false })
  public finished_on?: string | null;

  /** Who confirmed the plan and when (runs with `confirmPlan`). */
  @Field({ is_required: false })
  public plan_approved_by?: string | null;

  @Field({ is_required: false })
  public plan_approved_on?: string | null;
}
