import type * as React from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Award,
  BarChart3,
  Bell,
  Bot,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Command,
  CornerDownLeft,
  Database,
  ExternalLink,
  Filter,
  FlaskConical,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  Grid3x3,
  Headset,
  Home,
  KeyRound,
  LayoutGrid,
  Megaphone,
  Menu,
  MessageSquare,
  PanelLeftClose,
  PanelLeftOpen,
  Pin,
  Presentation,
  Puzzle,
  Receipt,
  Rows3,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Tv,
  User,
  UserX,
  Users,
  Video,
  Webhook,
  X,
} from 'lucide-react';

export const SHELL_ICONS = {
  Activity,
  Award,
  BarChart3,
  Bell,
  Bot,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Command,
  CornerDownLeft,
  Database,
  ExternalLink,
  Filter,
  FlaskConical,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe,
  Grid3x3,
  Headset,
  Home,
  KeyRound,
  LayoutGrid,
  Megaphone,
  Menu,
  MessageSquare,
  PanelLeftClose,
  PanelLeftOpen,
  Pin,
  Presentation,
  Puzzle,
  Receipt,
  Rows3,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  Tv,
  User,
  UserX,
  Users,
  Video,
  Webhook,
  X,
} satisfies Record<string, LucideIcon>;

export type ShellIconName = keyof typeof SHELL_ICONS;

export type ShellIconType = ShellIconName | LucideIcon | React.ComponentType<{ className?: string }>;

export function resolveShellIcon(icon: ShellIconType | undefined): React.ComponentType<{ className?: string }> {
  if (!icon) return Activity;
  if (typeof icon === 'string') {
    return SHELL_ICONS[icon as ShellIconName] ?? Activity;
  }
  return icon;
}
